### ISSUE TITLE
Testanwendung

### ISSUE THREAD

**Issue by Pluettmann** [Pluettmann/oostubs#1]
Die Testanwendung funktioniert noch nicht.
Außerdem scheint o_stream noch nicht bugfrei zu sein.

Es wird bspw. kein "!" geprinted

**Comment by Pluettmann** [comment]
Normale Ausgabe funktioniert jetzt. Sobald ein keyctrl objekt erstellt wird, jedoch nicht. o_stream ist jetzt auch bugfrei

**Comment by Pluettmann** [comment]
Fertig

**Comment by Jtelljohann** [comment]
Easy
